### ISSUE TITLE
Progress bar overlay does not disappear when game window or ACT are not in focus.

### ISSUE THREAD

**Issue by Zireael** [anoyetta/ACT.SpecialSpellTimer#10]
Progress bar overlay does not disappear when game window or ACT are not in focus. For example, when I Alt+Tab to Firefox or Skype window, I want the overlay to disappear, and appear again when I go back to game window. Picture of the problem below:
![buffs2](https://cloud.githubusercontent.com/assets/3856578/8917375/8c8f9e30-34a9-11e5-9569-ea75c7b95f48.png)

**Comment by Deadspace2** [comment]
Can confirm this is an issue, otherwise the plugin is amazing, Would love to see this fixed.
