### ISSUE TITLE
Option

### ISSUE THREAD

**Issue by Shadow-virus** [anoyetta/ACT.SpecialSpellTimer#15]
Hello
it would be possible to add the option tickers to spell time and the option time spell to ticker example I would position each spell timers or I want to make disappear the spell time (Matching log text to hide)

**Comment by Shadow-virus** [comment]
In Spell Time plz add (Matching log text to hide)

**Comment by anoyetta** [comment]
Isn't it settled by minus extension?

**Comment by Shadow-virus** [comment]
no i want force hide Spell timer with (Matching log text to hide) http://i.imgur.com/WznIPBp.png
really sorry for my bad english ^^, hard to explain in other language.

**Comment by irecinius** [comment]
Dragon - Blood of the dragoon

Wheeling trust +15secs
Fang and Claw +15segs
Geirskogul -10segs << No place to put...

**Comment by anoyetta** [comment]
Setting for "Blood of the Dragon".

Regex → ON
Extend1. You use  (Fang and Claw| Wheeling Thrust) +15s
Extend2. You use Geirskogul -10s

**Comment by Shadow-virus** [comment]
why you close you have even responded to my request ...

**Comment by Shadow-virus** [comment]
why you close you have even responded to my request ...
