### ISSUE TITLE
一定時間後に鳴らすサウンドが再生されない場合がある

### ISSUE THREAD

**Issue by madogiwa** [anoyetta/ACT.SpecialSpellTimer#25]
1.13.1で「ログにマッチしてn秒後に鳴らすサウンド」などが再生されないことがあります。

33e35ed1f0ee09516fec946b5c748879afb29bc1 での変更により、ログがない場合にマッチング処理を行わなくなったことから、後半にあるサウンド再生の処理も行われない場合があることが原因と思われます。

**Comment by anoyetta** [comment]
たしかにそうだわ。
ログがないときに2スレッド起こすのもどうかなと思って抜けるようにしたんだけど、ｎ秒後のマッチングのために全スペルと全テロップを舐めないといけないから、抜けないで普通に処理しておくのが良さそうね
