### ISSUE TITLE
1.13.xでCPU負荷が以前より高くなる

### ISSUE THREAD

**Issue by madogiwa** [anoyetta/ACT.SpecialSpellTimer#26]
1.12.1と比較してみたところ、1.13.3でCPU使用率が数倍高くなりました。

下記はスペル8個（アイコン有り）の時の値です。いずれもリキャスト中の値で、非リキャスト中はほぼ0%となります。

* 1.13.3　18〜20%
* 1.12.1　4〜5%

これは 88483962d045c51f7d48fc978764cf36aac3bb8f でRefreshWindowTimerが10msごとになっているため、描画負荷が高くなることが原因ではないかと思います。

試しに1.13.3に下記の変更を加えて試してみたところ、CPU使用率は1.12.1と同程度（4〜5%）となりました。

　RefreshWindowTimerの実行間隔　10ms => RefreshInterval(100msに設定)
　WatchLogTimerの実行間隔　RefreshInterval => 10ms

**Comment by anoyetta** [comment]
やっぱり描画も重いんですな。
描画関係の処理内容も見なおす必要がありそうですね。

Windowの更新間隔は短めにしたいです。
というのは、60fpsで更新させようとすると約15msを更新間隔とする必要があります。
微妙な変化ですが10msで描画させた場合、バーの動きはより滑らかに見えます。

とはいえ、現状で処理間隔を詰めると負荷的に不味そうなので描画周りを最適化するまでは100ms程度にしておこうかと思います。
