### ISSUE TITLE
Focus target Overlay comes up when no focus target is selected

### ISSUE THREAD

**Issue by EtherImperial** [anoyetta/ACT.SpecialSpellTimer#38]
When selecting a target, the focus target overlay comes on screen without a focus target chosen.  The focus target overlay does not disappear when target is no longer selected.

**Comment by Griever92** [comment]
This is not an issue with this plugin.
Refer to https://github.com/ravahn/FFXIV_ACT_Plugin/issues/51

**Comment by EtherImperial** [comment]
You are correct, got confused as to what plugin i was looking at
