### ISSUE TITLE
Overwrite Spell Timers with same name(s)

### ISSUE THREAD

**Issue by Griever92** [anoyetta/ACT.SpecialSpellTimer#4]
Attempting to configure a Spell Timer for Thunder(I/II/III) on Black Mage, as each level of Thunder has a different duration.

Created 3 individual Spell Timers, each using "Spell Name" Thunder, and matching text as:
* You cast Thunder
* You cast Thunder II
* You cast Thunder III

When casting Thunder, timer shows as expected.
When casting Thunder II, timer for both Thunder (1) and (2) appear.
When casting Thunder III, timer for all 3 versions appears.

===

Changed "priority" of timers, since all 3 timers have the same name, highest priority (smaller as per options) should only ever be visible in case of duplicate.
No effect, all 3 timers continue to appear when casting Thunder III.

===

Attempted to define exact string matches. (Using Regex)
* ^You cast Thunder$
* ^You cast Thunder II$
* ^You cast Thunder III$

No spell timers appear when using standard regex formatting (above).

**Comment by danakj** [comment]
You cast Thunder II.$ ?

Theres other stuff befroe it in the act log. And there's a period at the end.

**Comment by Griever92** [comment]
Yes, this is normal of Regex.
^ Indicates the beginning of what should be matched
$ Indicates the end.

Essentially, I am asking it to match the string exactly, preventing "Thunder" from matching when it sees "Thunder III"

**Comment by Griever92** [comment]
Issue is also occurring with Bio/Bio II on SMN/SCH
(See Below)

1) No Timers Active/No Spells Cast
![1](https://cloud.githubusercontent.com/assets/7936026/7174386/5e1423b8-e3c4-11e4-8375-a73bb31fb610.PNG)

2) Bio Cast - Timer for Bio Active
![2](https://cloud.githubusercontent.com/assets/7936026/7174387/5e171280-e3c4-11e4-925e-214944d7d306.PNG)

3) Bio Wears Off - Timer for Bio Ends
![3](https://cloud.githubusercontent.com/assets/7936026/7174391/83328ff4-e3c4-11e4-8d7e-ec379bdb144b.PNG)

4) Bio II Cast - Timer for Bio AND Bio II Active
![4](https://cloud.githubusercontent.com/assets/7936026/7174389/5e28700c-e3c4-11e4-9f0b-1941c273e0f7.PNG)

My spell timers are configured as follows:
![bio](https://cloud.githubusercontent.com/assets/7936026/7174431/352804aa-e3c5-11e4-9277-484f4a44d8d3.PNG)
![bio2](https://cloud.githubusercontent.com/assets/7936026/7174432/352a56ba-e3c5-11e4-9e73-7d0c417b6b13.PNG)

**Comment by Griever92** [comment]
Thunder Timer Issue

1) Thunder Cast - Timer for Thunder Active
![1](https://cloud.githubusercontent.com/assets/7936026/7174582/9f065f0a-e3c7-11e4-8e5f-ba9e905a5c41.PNG)

2) Thunder Wears Off - Timer for Thunder ends
![2](https://cloud.githubusercontent.com/assets/7936026/7174583/9f077480-e3c7-11e4-8a9e-2707d4616489.PNG)

3) Thunder II Cast - Timers for Thunder AND Thunder II active (even though same name)
![3](https://cloud.githubusercontent.com/assets/7936026/7174584/9f0dc164-e3c7-11e4-894b-1b75b3a597e7.PNG)

4) Thunder Wears Off - Timer(s) for Thunder end
![4](https://cloud.githubusercontent.com/assets/7936026/7174585/9f11ca66-e3c7-11e4-88db-552b1b0dbeb5.PNG)

5) Thunder III Cast - Timers for Thunder, Thunder II AND Thunder III active (even though same name)
![5](https://cloud.githubusercontent.com/assets/7936026/7174586/9f137f3c-e3c7-11e4-8426-b0f00c89a536.PNG)

===

Additionally, here are my spell timer settings for Thunder / Thunder II / Thunder III
![thunder1](https://cloud.githubusercontent.com/assets/7936026/7174594/bf8b77ec-e3c7-11e4-8699-48f3a046a9c9.PNG)

![thunder2](https://cloud.githubusercontent.com/assets/7936026/7174595/bfa379aa-e3c7-11e4-978e-6526ac4762ee.PNG)

![thunder3](https://cloud.githubusercontent.com/assets/7936026/7174596/bfaacade-e3c7-11e4-8593-1d61cfebf8e3.PNG)

**Comment by Griever92** [comment]
Also affected by this:

Aero / Aero II
Miasma / Miasma II

**Comment by anoyetta** [comment]
Please try these.

You cast Thunder\.$
You cast ThunderII\.$
You cast Thunder|||\.$

Use Regex is on.
