### ISSUE TITLE
画面の更新間隔の設定が反映されない？

### ISSUE THREAD

**Issue by alalwww** [anoyetta/ACT.SpecialSpellTimer#43]
画面の更新間隔の値は、[ログ処理間隔として使用されていて](https://github.com/anoyetta/ACT.SpecialSpellTimer/blob/master/ACT.SpecialSpellTimer/SpellTimerCore.cs#L117)、実際の画面の更新間隔は[100ms固定](https://github.com/anoyetta/ACT.SpecialSpellTimer/blob/master/ACT.SpecialSpellTimer/SpellTimerCore.cs#L108)になってますが、これは想定通りですか？

どちらも任意に設定できて良さそうな気がするので、設定画面から変更できるような修正を行ってもいいでしょうか？

**Comment by anoyetta** [comment]
こちらも修正して良いですよ。
これは、元々はログと画面の更新は同一のタイマでした。途中で分離したのですが、設定を作るのがめんどくさかったのと、ユーザには分かりづらいと思ったのでUIで変えられるのは1つ、片方は推奨値で固定としただけです。
