### ISSUE TITLE
「延長するマッチングワード」によるマッチがインスタン化に対応しない

### ISSUE THREAD

**Issue by questonex** [anoyetta/ACT.SpecialSpellTimer#50]
「スペルの名前(表示テキスト)が異なる場合にインスタンス化する」設定が有効な時に、
「延長するマッチングワード」にてマッチすると、マッチしたインスタンスだけではなく、
そのスペル全てのタイマーが延長されてしまいます。

例えば、以下のような設定の時、
・「スペルの名前」が "$1 Foo"
・「ログに対するマッチングワードが "(.) is Foo"
・「延長するマッチングワード」が "(.) is Bar"
次の3行のログが来たとします。
"A is Foo"
"B is Foo"
"A is Bar"
このとき "A Foo" および "B Foo" という名前のタイマーが順に生成されますが、
3 行目の "A is Bar" で "A Foo" だけではなく "B Foo" のタイマーも延長されてしまいます。

**Comment by anoyetta** [comment]
了解しました。確認します。

**Comment by anoyetta** [comment]
確認しましたが、現在の仕組上、どうしようもないですね。

インスタンス化は、単純に正規表現によって埋め込まれたスペル名が既存のものと異なっていたら新しいインスタンスを生成する という仕組になっています。「誰に」作用したスペルだから、新しいインスタンスを作るという仕組ではないです。

よって、使用者側はマッチング時の$1と延長時の$1は作用した対象を示しており、同じものである。同じ対象に対して作用したスペルのみ延長して欲しいと考えても、アプリ側はそれが同一のものであるとは認識していません（現状、認識するように作っていません）

**Comment by anoyetta** [comment]
前述のような仕組になっていることで、具体的な不都合があるようならばそれに合わせて対策を行うことも出来るかと思います。

"A is Foo" 
等の汎用の例ではなく、ゲーム内で実際に発生している不都合な例を挙げてもらっても良いですか？
それを見れば何らかの対応策を思いつくかもしれません。

**Comment by questonex** [comment]
> ゲーム内で実際に発生している不都合な例を挙げてもらっても良いですか？

すみません、実は FFXIV ではなく、別のゲームで利用させていただいております。ですので、現状こういう仕様であるということでしたら、改修をお願いするのもどうかと思いますので、この件はこれにてということで結構です。丁寧な回答、どうもありがとうございました。

ちなみに、Spell ではなく (De)Buff Timerとして使うことを考えていました。(De)Buff はキャラ(敵含む)ごとに別タイマーですので、インスタンス生成することで実現できそうだったのですが、(De)Buff は Spell と違って時間前に消されることがあり、その「消えました」ログを延長マッチに引っかけて -999 秒することでバーを消す、ということをしようとしていました。

**Comment by questonex** [comment]
とはいえ、せっかくなのでソースコードを調べてみたところ、
延長マッチ部分で replacedTitle と spell.SpellTitleReplaced が不一致の場合は continue する、
という数行の簡単なロジック追加で目的が達成できました。インスタンス化オン前提になりますが。
同じことをしたい人がいたら参考になるかもなので、コメント残しておきます。お騒がせしました。

**Comment by anoyetta** [comment]
単純に「延長マッチ部分で replacedTitle と spell.SpellTitleReplaced が不一致の場合は continue する」では不都合があるので、真面目に実装してみました。

正規表現マッチングでグループ名"target"と指定した場合は、その該当文字列をスペルインスタンスごとに記憶するようにしました。延長のマッチング時にも同様にグループ名"target"を指定することで、当初のマッチング時にキャプチャーした対象に対してだけ延長を判定できるようにしました。

DQXはプレイしていないので分かりませんが
スペル名
バイキルト => ${target}

マッチングキーワード
(?<target>.+?)の こうげき力が (少し|かなり) あがった！

延長キーワード
(?<target>.+?)の こうげき力アップの 効果延長！

これでインスタンス化して汎用的に使えるようになったと思います。

**Comment by questonex** [comment]
どうも大変お手数をおかけしました、無事に期待通りの動作になりました。
ありがとうございました。
