### ISSUE TITLE
matching log text to hide

### ISSUE THREAD

**Issue by hbq0449** [anoyetta/ACT.SpecialSpellTimer#51]
please add an function to hide the spell icon when log text was matched.

Sometimes, I just want to know some skill has been ready to use, when it's ready, I need it's icon to show.
There is no way to do that now.

so please add an function to hide the spell icon when log text was matched. with the Always show option, I can make the icon show when the skill is ready to use

or add an option to adjust the "brightness" of the icon with the option: 
"During the recast time reduce brightness of icon". Transparency will be better.

**Comment by anoyetta** [comment]
It was implemented.
"During the recast time reduce brightness of icon"

**Comment by hbq0449** [comment]
Sorry, I didn't try that one. It's funny that I use the same wording but not notice the option. Sorry again, and I will try that option today, and come back later if I have anything to add. 

Thanks.

**Comment by anoyetta** [comment]
I implemented, just now.

Try it. ver 1.15.11
https://github.com/anoyetta/ACT.SpecialSpellTimer/releases/tag/v1.15.11

**Comment by hbq0449** [comment]
Thanks! I just received the Release notice. 

Great work! ^_^ ! Thanks!
