### ISSUE TITLE
多人数コンテンツにおいてタイマーが遅延することについて

### ISSUE THREAD

**Issue by spelyum** [anoyetta/ACT.SpecialSpellTimer#52]
こんにちわ。いつも便利に使わせていただいてます。

PCの性能に依存する問題ですが、クリスタルタワー、マハ関連など24人コンテンツにおいて正規表現ONが含まれるタイマーを動作させた場合に、処理が追いつかずログの検知、タイマーの開始が遅延することがあります。

24人コンテンツでは動作させないようにする手段として、ゾーンを限定するオプションが存在しますが、ゲームアップデート～FF14プラグインの対応までゾーンビューに表示されないために、4人用IDや8人用レイドなどもプラグインが対応するまで動作しなくなってしまいます。

そこで、「選択したゾーン以外に限定する」オプションの追加など各自で対策可能になる手段の追加検討をお願いします
よろしくお願いします。

**Comment by anoyetta** [comment]
レポートありがとうございます。

フィルター機能の拡充については作業量が大きいため、まずは大本の問題である遅延対策を行おうと考えています。私も昨日極ソフィアにいって、検知が遅れるまたは検知されないという現象に遭遇したため必要性を感じています。

原因としては、先般行った不具合対策で「ヒット後ｎ秒後に再生するサウンドが遅延する不具合を修正した」というのがあります。実は、これによって負荷が若干増える（ただしやらなければｎ秒後のサウンドが正常に動作しない）ことが分かっておりまして、これ近辺が怪しいと考えています。

**Comment by anoyetta** [comment]
まだプレリリースですが、これで改善する予定です
https://github.com/anoyetta/ACT.SpecialSpellTimer/releases/tag/v1.16.7

**Comment by anoyetta** [comment]
正式リリースにしました。
プレリリース版とは中身が変わっているのでプレリリース版を使っている場合は入れ替えてください。

パフォーマンスはこれで大丈夫でないかと思います。
