### ISSUE TITLE
占星術士スキル作用不能

### ISSUE THREAD

**Issue by KOKOLALAMA** [anoyetta/ACT.SpecialSpellTimer#53]
すみません , ME 日本語 差

< me >に「ドロー：(アーゼマの均衡|世界樹の幹|オシュオンの矢|ハルオーネの槍|サリャクの水瓶|ビエルゴの塔)」の効果。

< me >に「ロイヤルロード：効果量増加」の効果。
< me>に「ロイヤルロード：効果時間増加」の効果。
< me>に「ロイヤルロード：効果範囲化」の効果。

以上 3.3 運行OK , 3.4 運行不能

===================================

白
gains the effect of 女神の加護 from < me>   :運行OK
< me>に「女神の加護」の効果。                 :運行OK

占
gains the effect of ルミナスエーテル from < me>      :3.4運行不能
< me>に「ルミナスエーテル」の効果。                    :3.3 運行OK , 3.4 運行不能

gains the effect of ライトスピード from < me>        :3.4運行OK
< me>に「ライトスピード」の効果。                      :3.3 運行OK , 3.4 運行不能

============================

白
< me>に「リジェネ」の効果。                                     :運行OK
gains the effect of リジェネ from < me>                       :運行OK

占
gains the effect of ノクターナルフィールド from < me>     :運行OK
< me>に「ノクターナルフィールド」の効果。                   :3.4 運行不能

gains the effect of アスペクト・ベネフィク from < me>    :運行OK
< me>に「アスペクト・ベネフィク」の効果。                  :3.4 運行不能

他人
白
<2>に「リジェネ」の効果。                            :運行OK
占
<2>に「アスペクト・ベネフィク」の効果。    :3.3 運行OK , 3.4 運行不能

< me> 文字消失..?

**Comment by anoyetta** [comment]
占星術師は私もプレイしています。
カードについては下記のような設定で3.4でも動作しています。設定してみてご確認ください。
<pre>
<me>に「.+ドロー：アーゼマの均衡」の効果
<me>に「.+ロイヤルロード：効果時間増加」の効果
<me>に「.+キープ：アーゼマの均衡」の効果
</pre>

**Comment by KOKOLALAMA** [comment]
新增 .+  運行OK
ありがとう！
