### ISSUE TITLE
Unable to Match Regex since 3.4

### ISSUE THREAD

**Issue by Griever92** [anoyetta/ACT.SpecialSpellTimer#54]
FFXIV Patch 3.4 introduced ability tagging in the chat log (seen below)
![ffxiv_dx11_2016-10-06_16-59-57](https://cloud.githubusercontent.com/assets/7936026/19173696/6ef30890-8be6-11e6-9e8b-09befdaa82d6.png)

Unfortunately, as a result, the log detection for triggering timers no longer works.
I've tried to define wildcards in my regex, but this does not resolve the issue.
Here's an example of a trigger I have setup. This worked without issue until patch 3.4
![advanced combat tracker_2016-10-06_17-02-43](https://cloud.githubusercontent.com/assets/7936026/19173738/d091c80c-8be6-11e6-9554-5d28288b6131.png)

**Comment by anoyetta** [comment]
From patch3.4 now tooltip symbol is added to the front of the skill name.
Therefore, you must change the pattern of the regular expression.
Please try the following pattern.

You lose the effet of [.]{0,3}Spire Dawn.
---
パッチ3.4からはスキル名の前にツールチップ用の記号が追加されるようになりました。
したがって、それに合わせて正規表現のパターンを変更しなければなりません。
下記のパターンを試してみてください。

ツールチップ用の記号は文字ではありません。したがって、[a-zA-Z]ではマッチしないのです。

**Comment by Shiriow** [comment]
Hello.
I've had the same problem and tried that but it still doesn't seem to be working.
Any idea why?

**Comment by Shiriow** [comment]
Nevermind doing
You lose the effect of .*Spire Drawn
fixed it

**Comment by Griever92** [comment]
Was able to resolve using:
`You lose the effect of .* Drawn`

Thank you

**Comment by anoyetta** [comment]
That's good !
