### ISSUE TITLE
Dragoon - Blood of the Dragon timer and extending / reducing

### ISSUE THREAD

**Issue by Xeiranis** [anoyetta/ACT.SpecialSpellTimer#7]
Heya, I'm trying to set up a Blood of the Dragon timer to extend by 15s when doing Fang and Claw and Wheeling Thrust but also reduce by 10s when using Geirskogul. Is there a way to do this within the two Matching log text for extending areas? Or even possibly add a third Matching log text for extending option? 

Sorry if it's a silly question but I've looked all over and can't find a solution. I appreciate any help you can provide.

**Comment by anoyetta** [comment]
Hi.
Thanks for using.

About blood of the dragon buff...

extend1: You used (Fang and Clow|Wheeling Thrust) +15s
extend2: You used Geirskogul -10s

When is this OK?

**Comment by Xeiranis** [comment]
Stopped playing for a while and just got back. Was trying to set this up again and remembered I asked about it back in August. 

So it's a bit late but, thank you this works perfectly. :)
