### ISSUE TITLE
Plugin Initialization failure

### ISSUE THREAD

**Issue by MikeMatrix** [anoyetta/ACT.SpecialSpellTimer#73]
![advanced combat tracker_2017-07-14_10-43-29](https://user-images.githubusercontent.com/1426581/28205238-7030d8fe-6881-11e7-96f4-2078638cc6fb.png)

Occurs when trying to load the plugin with version >=1.18.8.
Tested with and without configuration being present.
Tested with and without other plugins being present.

If I have time I might look over the code, but maybe you'll find something before I do.

**Comment by Zoralback** [comment]
Having the same issue on Windows 10 Creator,only happens with >=1.18.8 too.

Can make the plugin start by deleting the "anoyetta" folder on %appdata% ,it creates an ACT.SpecialSpellTimer.config file.

After the plugin is successfully started if I disable it and re-enable or restart ACT it it will crash as "Object reference not set to an instance of an object"

Act log

 ```
***** 2017-07-14T14:10:56 - Enabling plugin: D:\Advanced Combat Tracker\ACT.SpecialSpellTimer.dll
***** 2017-07-14T14:10:56 - Plugin Initialization Failed
System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
   à ACT.SpecialSpellTimer.SpecialSpellTimerPlugin.Advanced_Combat_Tracker.IActPluginV1.InitPlugin(TabPage pluginScreenSpace, Label pluginStatusText)
   à Advanced_Combat_Tracker.FormActMain.pluginPanelEnabledChecked(Object sender, EventArgs e)
 à Advanced_Combat_Tracker.FormActMain.WriteExceptionLog(Exception ex, String MoreInfo)
   à Advanced_Combat_Tracker.FormActMain.pluginPanelEnabledChecked(Object sender, EventArgs e)
   à System.Windows.Forms.CheckBox.OnCheckedChanged(EventArgs e)
   à System.Windows.Forms.CheckBox.set_CheckState(CheckState value)
   à System.Windows.Forms.CheckBox.OnClick(EventArgs e)
   à System.Windows.Forms.CheckBox.OnMouseUp(MouseEventArgs mevent)
   à System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   à System.Windows.Forms.Control.WndProc(Message& m)
   à System.Windows.Forms.ButtonBase.WndProc(Message& m)
   à System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   à System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   à System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   à System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   à System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   à System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   à Advanced_Combat_Tracker.ActLoader.Main(String[] args)
*****
***** 2017-07-14T14:10:57 - An exception occurred at the end of ACT.SpecialSpellTimer plug-ins.
System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
   à ACT.SpecialSpellTimer.SpecialSpellTimerPlugin.Advanced_Combat_Tracker.IActPluginV1.DeInitPlugin()
 à Advanced_Combat_Tracker.FormActMain.WriteExceptionLog(Exception ex, String MoreInfo)
   à ACT.SpecialSpellTimer.SpecialSpellTimerPlugin.Advanced_Combat_Tracker.IActPluginV1.DeInitPlugin()
   à Advanced_Combat_Tracker.FormActMain.pluginPanelEnabledChecked(Object sender, EventArgs e)
   à System.Windows.Forms.CheckBox.OnCheckedChanged(EventArgs e)
   à System.Windows.Forms.CheckBox.set_CheckState(CheckState value)
   à System.Windows.Forms.CheckBox.set_Checked(Boolean value)
   à Advanced_Combat_Tracker.FormActMain.pluginPanelEnabledChecked(Object sender, EventArgs e)
   à System.Windows.Forms.CheckBox.OnCheckedChanged(EventArgs e)
   à System.Windows.Forms.CheckBox.set_CheckState(CheckState value)
   à System.Windows.Forms.CheckBox.OnClick(EventArgs e)
   à System.Windows.Forms.CheckBox.OnMouseUp(MouseEventArgs mevent)
   à System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   à System.Windows.Forms.Control.WndProc(Message& m)
   à System.Windows.Forms.ButtonBase.WndProc(Message& m)
   à System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   à System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   à System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   à System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   à System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   à System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   à Advanced_Combat_Tracker.ActLoader.Main(String[] args)
*****
```

**Comment by anoyetta** [comment]
Thanks for the report.
I forgot to create it when the directory does not exist.

I'll fix it in the next version.

**Comment by Zoralback** [comment]
Hello,and thanks for the fast reponse

Unfortunately 1.19.1 did not fix anything for me,i'm adding a video of the problem for reference,might help you

https://streamable.com/r3o3b

As you can see in the video the plugin initializes normally when no config folder is present ,but one the folder is there it will not start again if disabled/restart act


I have no knowledge in development so I can't really pinpoint myself where the issue is really coming from,sorry for that

**Comment by MikeMatrix** [comment]
Error persist on my side as well.

**Comment by Waxilium** [comment]
Hey there. First of all: MANY thanks for this great addition to ACT.

2nd: Even with version 1.19.2 the afore mentioned error (sadyl) still exists.

Thx in advance for a solution.

**Comment by Zoralback** [comment]
Ok so I think I found the origin of the issue and a workaround to make newer versions start,**can only confirm for myself**

The plugin will start successfuly if the **Font** config line in **%appdata%/anoyetta/ACT/ACT.SpecialSpelltimer.config** is deleted 
![notepad _2017-07-17_23-54-25](https://user-images.githubusercontent.com/30176859/28291590-627649f2-6b4b-11e7-8581-788cf7778312.jpg)

By deleting this line the plugin will start but after closing the Font line will come back and make the plugin crash if restarted,so you need to delete it before opening ACT/enabling the plugin

**Comment by Waxilium** [comment]
Thx for the quick release of 19.3 

Don't know if it is only me but the error sadly still persits. 
Uninstalled ACT, deleted all old files. Re-Downloaded everything and set up all from scratch.

**Comment by Zoralback** [comment]
v1.19.4 fixed the issue for me !

**Comment by Waxilium** [comment]
Well. Can't test it right now, but your post gives me hope.

**Comment by MikeMatrix** [comment]
Fixed.
