### ISSUE TITLE
XIVDBDownloader error/crash

### ISSUE THREAD

**Issue by hdqk** [anoyetta/ACT.SpecialSpellTimer#78]
It crashes when it reaches the Samurai abilities that have a colon (:) in the name, namely "7490_Hissatsu: Shinten.png". My guess is it's an issue with Windows not handling colons in filenames. This may only happen when downloading Actions in English (EN).

**Comment by anoyetta** [comment]
Fix int to remove invalid characters  for file names.

**Comment by anoyetta** [comment]
Try this.
https://github.com/anoyetta/ACT.SpecialSpellTimer/releases/tag/v1.20.10

**Comment by hdqk** [comment]
That worked, thank you.
