### ISSUE TITLE
Failed refreshPetID?

### ISSUE THREAD

**Issue by alalwww** [anoyetta/ACT.SpecialSpellTimer#80]
`<petid>` が利用できないようです。
LogタブのPlaceholdersの一覧にも出てきていないので、更新が行えていないように思えます。

コード見ただけだと呼ばれないことはないようなきがするので、[ここのcatch](https://github.com/anoyetta/ACT.SpecialSpellTimer/blob/master/ACT.SpecialSpellTimer/Models/TableCompiler.cs#L741-L743)で何か失敗したのがログに残らず消えちゃってるかも？

時間が取れたら検証したかったんですが、ちょっとなさそうだったので Issue だけ。:bow:

**Comment by anoyetta** [comment]
わかりました。見ておきます

**Comment by anoyetta** [comment]
例外ではなく凡ミスで条件式が反転していてペットIDの取得に入っていませんでしたね。
直しておきました。
