### ISSUE TITLE
点滅的機能の

### ISSUE THREAD

**Issue by KeisenKKR** [anoyetta/ACT.SpecialSpellTimer#81]
今回の技術的革新で警戒色対応がなされましたが
視覚的効果でアイコンの点滅的機能の実装は可能でしょうか。

**Comment by anoyetta** [comment]
可能です。

**Comment by anoyetta** [comment]
blinking of icon and the progress bar is coming soon.

**Comment by KeisenKKR** [comment]
すばらしい革新的實施ありがとうございます。
