### ISSUE TITLE
Progress not shows on bar

### ISSUE THREAD

**Issue by sergserg2** [anoyetta/ACT.SpecialSpellTimer#83]
Progress bars are all white (no porgress) after change to 1.21.2 (and 1.22.3 also). Numerical counters are OK, but no progress on bars (I've checked normal and reverse directions).

**Comment by sergserg2** [comment]
V1.21.11, bars shows no progress all time.
Please look at this [video](https://youtu.be/5TYSjMp8pt4)
Demolish is starting counter, digits are ok, but no progress on bar.

**Comment by NGAbsalon** [comment]
Problem is its a white bar on white background.

You could add an option to define the bar background color to avoid this

**Comment by anoyetta** [comment]
v1.22.0
https://github.com/anoyetta/ACT.SpecialSpellTimer/releases/tag/v1.22.0
You can change background color of progress bar.

**Comment by sergserg2** [comment]
I check v1.22.0, background is grey and progress is visible.
Thank you.
