### ISSUE TITLE
[Feature request] "Hide spell timers after completion" setting individual for each timer

### ISSUE THREAD

**Issue by Zireael** [anoyetta/ACT.SpecialSpellTimer#9]
I would like to ask for "Hide spell timers after completion" setting to be available separately for each individual timer in [Spell Timers] tab.
The reason is, for some timers I want to see when their progress bar is ready - using abilities 'on recast'. But for less important abilities, when they become ready and I don't cast them again, I don't care much to see their 'Ready!' progress bar.

Also, when using [Spell Timer] in "Reverse direction" mode, once the progress bar reaches zero, I don't want to see the progress bar again until I cast the ability again. For example, someone would like  to see progress bar of [Invincible], [Dreadwyrm Trance], [Greased Lightning], [Dissipation] ability. But once those abilities are over, they don't want to see their progress bar any more.

In attached image, I want to see Aetherflow being ready always. Virus and Eye for an Eye to disappear 5 seconds after becoming "Ready". And progress bar for Dissipation I want to disappear after reaching zero.
![buffs](https://cloud.githubusercontent.com/assets/3856578/8917279/03ea7438-34a9-11e5-8d28-defab53f68f0.png)

**Comment by anoyetta** [comment]
Isn't it settled by using "Always show" checkbox ?
