### ISSUE TITLE
possible InvalidOperationException due to modifying collection during iteration

### ISSUE THREAD

**Issue by Airex** [anoyetta/ACT.SpecialSpellTimer#92]
https://github.com/anoyetta/ACT.SpecialSpellTimer/blob/ed50380da50f6d6146cdd91fb748b178dee70133/ACT.SpecialSpellTimer.Core/Views/SpellPanelWindow.xaml.cs#L327

ToArray or similar required

**Comment by anoyetta** [comment]
thank you.
oh, i made mistakes.
