### ISSUE TITLE
A backreference for Tickers duration ?

### ISSUE THREAD

**Issue by NightClawZ** [anoyetta/ACT.SpecialSpellTimer#96]
Hello,
Thank you for your work, it is really useful :)
Do you think it would be possible to add a backreference `(?<duration>\d+)` for tickers like you did for timers ? 
Thank you in advance.

**Comment by anoyetta** [comment]
In Ticker, Backreference by duration does not work.
you can use Spell.

**Comment by NightClawZ** [comment]
Yes I know that, thank you. I was just asking if it could be added as well for tickers :)

**Comment by anoyetta** [comment]
Spell is upwardly compatible with Ticker.
I do not feel the significance of adding duration to Ticker.

**Comment by NightClawZ** [comment]
Okay, thank you for your answer.
