### ISSUE TITLE
Zone filtering improvement suggestions

### ISSUE THREAD

**Issue by NightClawZ** [anoyetta/ACT.SpecialSpellTimer#97]
Hello,
Do you think it would be possible to add "open world zone" and reorganize the UI as follow ? 
```
[ ] All zones
	[ ] Gridania
		[ ] South Shroud
		...
	[X] Limsa Lominsa
		[X] Mist
		...
	[ ] Yanxia
		...
	...
	[ ] Dungeons
		[ ] Sastasha
		...
	[ ] Raids
		[X] Deltascape 1.0
		...
	[ ] Alliance Raids
		[ ] Dun Scaith
		...
	[ ] Frontlines
		[ ] Seal Rock
		...
	[X] Eureka
		[X] Anemos
		...
```
We would check one zone and or its subzones. 
This would help a lot :)

**Comment by anoyetta** [comment]
The addition of Zone depends on the internal definition of FFXIV_ACT_Plugin.
However, it is also possible to describe arbitrarily in a file and add it by the user.
resources/Zones.csv

As for UI, I do not feel necessary because there is no complicated check division.

**Comment by NightClawZ** [comment]
Or maybe sort the zones by name then ? :)

**Comment by anoyetta** [comment]
Currently sort in the order use frequently.
For example, the most recently implemented RAID is first.

I do not think this sort order is particularly inconvenient.

**Comment by NightClawZ** [comment]
Well, actually (ACT.Hojoring v5.5.8) I see the following : 
- the Fractal Continuum (Hard)
- Sohm Al (Hard) 
- the Great Gubal Library (Hard) 
- Hullbreaker Isle (Hard)
- the Lost City of Amdapor (Hard)
- Pharos Sirius (Hard)
- ...
  
It has been a very long time since I went to Pharos Sirius and yet it is relatively high in the list. 
Sigmascape is way behind those and I do them on a weekly basis.
I see no logical order in that sorting.

Here, a [screenshot](https://i.imgur.com/VFNr3nT.png).

**Comment by anoyetta** [comment]
Optimization of sort order does not work in English.
I'll fix it.

**Comment by anoyetta** [comment]
this is fixed zone list.

![image](https://user-images.githubusercontent.com/8295826/40148228-f2b19b52-59a7-11e8-9236-2f83b8cde222.png)

**Comment by NightClawZ** [comment]
Thank you. Can you tell me when the fix will be released so I can test it ? Looks awesome !
